"""empty message

Revision ID: 1330177f7777
Revises: f7cddf016e6d
Create Date: 2021-03-17 23:23:09.527030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1330177f7777'
down_revision = 'f7cddf016e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reviews', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('cabernet_sauvignon', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('cabernet_sauvignon_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('chardonnay', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('gewurztraminer', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('grenache_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('malbec', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('merlot', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('moscato', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mourvedre_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('nebbiolo', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pinot_grigio', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pinot_noir', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pinot_noir_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('provence_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('red', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('riesling', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sangiovese', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sangiovese_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sauvignon_blanc', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('semillon', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('syrah_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('syrah_shiraz', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tavel_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tempranillo_rose', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('white', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('zinfandel', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('zinfandel_rose', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zinfandel_rose')
    op.drop_column('users', 'zinfandel')
    op.drop_column('users', 'white')
    op.drop_column('users', 'tempranillo_rose')
    op.drop_column('users', 'tavel_rose')
    op.drop_column('users', 'syrah_shiraz')
    op.drop_column('users', 'syrah_rose')
    op.drop_column('users', 'semillon')
    op.drop_column('users', 'sauvignon_blanc')
    op.drop_column('users', 'sangiovese_rose')
    op.drop_column('users', 'sangiovese')
    op.drop_column('users', 'rose')
    op.drop_column('users', 'riesling')
    op.drop_column('users', 'red')
    op.drop_column('users', 'provence_rose')
    op.drop_column('users', 'pinot_noir_rose')
    op.drop_column('users', 'pinot_noir')
    op.drop_column('users', 'pinot_grigio')
    op.drop_column('users', 'nebbiolo')
    op.drop_column('users', 'mourvedre_rose')
    op.drop_column('users', 'moscato')
    op.drop_column('users', 'merlot')
    op.drop_column('users', 'malbec')
    op.drop_column('users', 'grenache_rose')
    op.drop_column('users', 'gewurztraminer')
    op.drop_column('users', 'chardonnay')
    op.drop_column('users', 'cabernet_sauvignon_rose')
    op.drop_column('users', 'cabernet_sauvignon')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    # ### end Alembic commands ###
