"""empty message

Revision ID: 3446a4325602
Revises: 1330177f7777
Create Date: 2021-03-17 23:35:07.102315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3446a4325602'
down_revision = '1330177f7777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('bourbon', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('brandy', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('cognac', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('gin', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('liqueurs', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('red', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('rose', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('rum', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('scotch', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('tequila', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('vodka', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('white', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('bourbon', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('brandy', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('cognac', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('gin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('liqueurs', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('rum', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('scotch', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tequila', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('vodka', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vodka')
    op.drop_column('users', 'tequila')
    op.drop_column('users', 'scotch')
    op.drop_column('users', 'rum')
    op.drop_column('users', 'liqueurs')
    op.drop_column('users', 'gin')
    op.drop_column('users', 'cognac')
    op.drop_column('users', 'brandy')
    op.drop_column('users', 'bourbon')
    op.drop_column('hosts', 'white')
    op.drop_column('hosts', 'vodka')
    op.drop_column('hosts', 'tequila')
    op.drop_column('hosts', 'scotch')
    op.drop_column('hosts', 'rum')
    op.drop_column('hosts', 'rose')
    op.drop_column('hosts', 'red')
    op.drop_column('hosts', 'liqueurs')
    op.drop_column('hosts', 'gin')
    op.drop_column('hosts', 'cognac')
    op.drop_column('hosts', 'brandy')
    op.drop_column('hosts', 'bourbon')
    # ### end Alembic commands ###
