"""empty message

Revision ID: 3c85eb5eb277
Revises: 3446a4325602
Create Date: 2021-03-17 23:43:13.381324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c85eb5eb277'
down_revision = '3446a4325602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('whiskey', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('whiskey', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whiskey')
    op.drop_column('hosts', 'whiskey')
    # ### end Alembic commands ###
